runtime: php55
api_version: 1

handlers:

# Accueil global
- url: /
  script: index.php

#===================================== /zone_1/Premier Zone =============================
#Accueil Premier zone
- url: /zone_1
  script: zone_1/views/Main/main.php

#Les ressources statiques
- url: /css
  static_dir: zone_1/web/css
- url: /js
  static_dir: zone_1/web/js
- url: /img
  static_dir: zone_1/web/img
- url: /fonts
  static_dir: zone_1/web/fonts
- url: /medias
  static_dir: zone_1/web/medias

#Insertion
- url: /zone_1/insert
  script: zone_1/controllers/Get/insert.php

#Connexion / Deconnexion
- url: /zone_1/login
  script: zone_1/var/login.php
- url: /zone_1/logout
  script: zone_1/var/logout.php

#Home Page
- url: /zone_1/home
  script: zone_1/views/Home/home.php

# les pages CO2, CO and NH3 
- url: /zone_1/home/co2
  script: zone_1/views/Co2/co2.php
- url: /zone_1/home/co
  script: zone_1/views/Co/co.php
- url: /zone_1/home/nh3
  script: zone_1/views/Nh3/nh3.php

# pour les historiques
- url: /zone_1/home/co2/histmin
  script: zone_1/views/Co2/histmin.php
- url: /zone_1/home/co2/histheure
  script: zone_1/views/Co2/histheure.php
- url: /zone_1/home/co2/deuxjours
  script: zone_1/views/Co2/deuxjours.php
- url: /zone_1/home/co2/hier
  script: zone_1/views/Co2/hier.php
- url: /zone_1/home/co2/tous
  script: zone_1/views/Co2/tous.php

# données pour la courbe co2
- url: /zone_1/home/co2/data
  script: zone_1/controllers/Co2/live-server-data.php
 # ======================= end Premier Zone ===================================


#Second Zone
- url: /zone_2
  script: /zone_2/public/main.php



