runtime: php55
api_version: 1

handlers:

# Accueil global
- url: /
  script: index.php

#================== Premier Zone ==================
# #Accueil Premiere zone
# - url: /zone_1
#   script: zone_1/app.yaml

#Les ressources statiques
- url: /css
  static_dir: web/css
- url: /js
  static_dir: web/js
- url: /img
  static_dir: web/img


# #Insertion
# - url: /zone_1/insert
#   script: zone_1/controllers/Get/insert.php

# #Connexion / Deconnexion
# - url: /zone_1/login
#   script: zone_1/var/login.php
# - url: /zone_1/logout
#   script: zone_1/var/logout.php

# #Home Page
# - url: /zone_1/home
#   script: zone_1/views/Home/home.php

# # les pages CO2, CO and NH3 
# - url: /zone_1/home/co2
#   script: zone_1/views/Co2/co2.php
# - url: /zone_1/home/co
#   script: zone_1/views/Co/co.php
# - url: /zone_1/home/nh3
#   script: zone_1/views/Nh3/nh3.php

# # pour les historiques de co2
# - url: /zone_1/home/co2/histmin
#   script: zone_1/views/Co2/histmin.php
# - url: /zone_1/home/co2/histheure
#   script: zone_1/views/Co2/histheure.php
# - url: /zone_1/home/co2/deuxjours
#   script: zone_1/views/Co2/deuxjours.php
# - url: /zone_1/home/co2/hier
#   script: zone_1/views/Co2/hier.php
# - url: /zone_1/home/co2/tous
#   script: zone_1/views/Co2/tous.php

# # pour les historiques de co
# - url: /zone_1/home/co/histmin
#   script: zone_1/views/Co/histmin.php
# - url: /zone_1/home/co/histheure
#   script: zone_1/views/Co/histheure.php
# - url: /zone_1/home/co/deuxjours
#   script: zone_1/views/Co/deuxjours.php
# - url: /zone_1/home/co/hier
#   script: zone_1/views/Co/hier.php
# - url: /zone_1/home/co/tous
#   script: zone_1/views/Co/tous.php

# # pour les historiques de nh3
# - url: /zone_1/home/nh3/histmin
#   script: zone_1/views/Nh3/histmin.php
# - url: /zone_1/home/nh3/histheure
#   script: zone_1/views/Nh3/histheure.php
# - url: /zone_1/home/nh3/deuxjours
#   script: zone_1/views/Nh3/deuxjours.php
# - url: /zone_1/home/nh3/hier
#   script: zone_1/views/Nh3/hier.php
# - url: /zone_1/home/nh3/tous
#   script: zone_1/views/Nh3/tous.php

# # données pour la courbe co2
# - url: /zone_1/home/co2/data
#   script: zone_1/controllers/Co2/live-server-data.php

# # données pour la courbe co
# - url: /zone_1/home/co/data
#   script: zone_1/controllers/Co/live-server-data.php

# # données pour la courbe nh3
# - url: /zone_1/home/nh3/data
#   script: zone_1/controllers/Nh3/live-server-data.php
#  # ================= end Premiere Zone ===========


# #=================== Seconde Zone ======================
# #Accueil Seconde zone
# - url: /zone_2
#   script: zone_2/app.yaml

# #Les ressources statiques
# - url: /css
#   static_dir: zone_2/web/css
# - url: /js
#   static_dir: zone_2/web/js
# - url: /img
#   static_dir: zone_2/web/img
# - url: /fonts
#   static_dir: zone_2/web/fonts
# - url: /medias
#   static_dir: zone_2/web/medias

# #Insertion
# - url: /zone_2/insert
#   script: zone_2/controllers/Get/insert.php

# #Connexion / Deconnexion
# - url: /zone_2/login
#   script: zone_2/var/login.php
# - url: /zone_2/logout
#   script: zone_2/var/logout.php

# #Home Page
# - url: /zone_2/home
#   script: zone_2/views/Home/home.php

# # les pages CO2, CO and NH3 
# - url: /zone_2/home/co2
#   script: zone_2/views/Co2/co2.php
# - url: /zone_2/home/co
#   script: zone_2/views/Co/co.php
# - url: /zone_2/home/nh3
#   script: zone_2/views/Nh3/nh3.php

# # pour les historiques de co2
# - url: /zone_2/home/co2/histmin
#   script: zone_2/views/Co2/histmin.php
# - url: /zone_2/home/co2/histheure
#   script: zone_2/views/Co2/histheure.php
# - url: /zone_2/home/co2/deuxjours
#   script: zone_2/views/Co2/deuxjours.php
# - url: /zone_2/home/co2/hier
#   script: zone_2/views/Co2/hier.php
# - url: /zone_2/home/co2/tous
#   script: zone_2/views/Co2/tous.php

# # pour les historiques de co
# - url: /zone_2/home/co/histmin
#   script: zone_2/views/Co/histmin.php
# - url: /zone_2/home/co/histheure
#   script: zone_2/views/Co/histheure.php
# - url: /zone_2/home/co/deuxjours
#   script: zone_2/views/Co/deuxjours.php
# - url: /zone_2/home/co/hier
#   script: zone_2/views/Co/hier.php
# - url: /zone_2/home/co/tous
#   script: zone_2/views/Co/tous.php

# # pour les historiques de nh3
# - url: /zone_2/home/nh3/histmin
#   script: zone_2/views/Nh3/histmin.php
# - url: /zone_2/home/nh3/histheure
#   script: zone_2/views/Nh3/histheure.php
# - url: /zone_2/home/nh3/deuxjours
#   script: zone_2/views/Nh3/deuxjours.php
# - url: /zone_2/home/nh3/hier
#   script: zone_2/views/Nh3/hier.php
# - url: /zone_2/home/nh3/tous
#   script: zone_2/views/Nh3/tous.php

# # données pour la courbe co2
# - url: /zone_2/home/co2/data
#   script: zone_2/controllers/Co2/live-server-data.php

# # données pour la courbe co
# - url: /zone_2/home/co/data
#   script: zone_2/controllers/Co/live-server-data.php

# # données pour la courbe nh3
# - url: /zone_2/home/nh3/data
#   script: zone_2/controllers/Nh3/live-server-data.php
#  # ================= end Premier Zone ===========