runtime: php55
api_version: 1

handlers:


#Accueil Seconde zone
- url: /
  script: views/Main/main.php

#Les ressources statiques
- url: /css
  static_dir: web/css
- url: /js
  static_dir: web/js
- url: /img
  static_dir: web/img
- url: /fonts
  static_dir: web/fonts
- url: /medias
  static_dir: web/medias

#Insertion
- url: /insert
  script: controllers/Get/insert.php

#Connexion / Deconnexion
- url: /login
  script: var/login.php
- url: /logout
  script: var/logout.php

#Home Page
- url: /home
  script: views/Home/home.php

# les pages CO2, CO and NH3 
- url: /home/co2
  script: views/Co2/co2.php
- url: /home/co
  script: views/Co/co.php
- url: /home/nh3
  script: views/Nh3/nh3.php

# pour les historiques de co2
- url: /home/co2/histmin
  script: views/Co2/histmin.php
- url: /home/co2/histheure
  script: views/Co2/histheure.php
- url: /home/co2/deuxjours
  script: views/Co2/deuxjours.php
- url: /home/co2/hier
  script: views/Co2/hier.php
- url: /home/co2/tous
  script: views/Co2/tous.php

# pour les historiques de co
- url: /home/co/histmin
  script: views/Co/histmin.php
- url: /home/co/histheure
  script: views/Co/histheure.php
- url: /home/co/deuxjours
  script: views/Co/deuxjours.php
- url: /home/co/hier
  script: views/Co/hier.php
- url: /home/co/tous
  script: views/Co/tous.php

# pour les historiques de nh3
- url: /home/nh3/histmin
  script: views/Nh3/histmin.php
- url: /home/nh3/histheure
  script: views/Nh3/histheure.php
- url: /home/nh3/deuxjours
  script: views/Nh3/deuxjours.php
- url: /home/nh3/hier
  script: views/Nh3/hier.php
- url: /home/nh3/tous
  script: views/Nh3/tous.php

# données pour la courbe co2
- url: /home/co2/data
  script: controllers/Co2/live-server-data.php

# données pour la courbe co
- url: /home/co/data
  script: controllers/Co/live-server-data.php

# données pour la courbe nh3
- url: /home/nh3/data
  script: controllers/Nh3/live-server-data.php

# formulaire de contact
- url: /contact_views
  script: views/Contact/contact.php
  
- url: /contact_action
  script: controllers/Contact/contact_action.php
  
 # ================= end Seconde Zone ===========
